name: CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    backend:
        name: Backend
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend

        steps:
            -   uses: actions/checkout@v4

            -   name: Install Rust toolchain
                uses: dtolnay/rust-toolchain@stable

            -   name: Cache dependencies
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.cargo/registry
                        ~/.cargo/git
                        backend/target
                    key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            -   name: Build
                run: cargo build --verbose

            -   name: Run tests
                run: cargo test --verbose

    frontend:
        name: Frontend
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend

        steps:
            -   uses: actions/checkout@v4

            -   name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: '18'
                    cache: 'npm'
                    cache-dependency-path: './frontend/package-lock.json'

            -   name: Install dependencies
                run: npm ci

            -   name: Build
                run: npm run build

            -   name: Type check
                run: npm run typescript
